export const GEO_ALIASES: Array<[alias: string, urlPath: string]> = [
  ["алатауский район", "almaty-alatauskij"],
  ["алатауском районе", "almaty-alatauskij"],
  ["алатауский", "almaty-alatauskij"],
  ["алмалинский район", "almaty-almalinskij"],
  ["алмалинском районе", "almaty-almalinskij"],
  ["алмалинский", "almaty-almalinskij"],
  ["ауэзовский район", "almaty-aujezovskij"],
  ["ауэзовском районе", "almaty-aujezovskij"],
  ["ауэзовский", "almaty-aujezovskij"],
  ["бостандыкский район", "almaty-bostandykskij"],
  ["бостандыкском районе", "almaty-bostandykskij"],
  ["бостандыкский", "almaty-bostandykskij"],
  ["жетысуский район", "almaty-zhetysuskij"],
  ["жетысуском районе", "almaty-zhetysuskij"],
  ["жетысуский", "almaty-zhetysuskij"],
  ["медеуский район", "almaty-medeuskij"],
  ["медеуском районе", "almaty-medeuskij"],
  ["медеуский", "almaty-medeuskij"],
  ["наурызбайский район", "almaty-nauryzbajskiy"],
  ["наурызбайском районе", "almaty-nauryzbajskiy"],
  ["наурызбайский", "almaty-nauryzbajskiy"],
  ["турксибский район", "almaty-turksibskij"],
  ["турксибском районе", "almaty-turksibskij"],
  ["турксибский", "almaty-turksibskij"],
  ["мкр аксай 1", "almaty-aujezovskij-mkr-aksay-1"],
  ["мкр аксай-1", "almaty-aujezovskij-mkr-aksay-1"],
  ["аксай 1", "almaty-aujezovskij-mkr-aksay-1"],
  ["аксай-1", "almaty-aujezovskij-mkr-aksay-1"],
  ["мкр аксай 2", "almaty-aujezovskij-mkr-aksay-2"],
  ["мкр аксай-2", "almaty-aujezovskij-mkr-aksay-2"],
  ["аксай 2", "almaty-aujezovskij-mkr-aksay-2"],
  ["аксай-2", "almaty-aujezovskij-mkr-aksay-2"],
  ["мкр аксай 3", "almaty-aujezovskij-mkr-aksay-3"],
  ["мкр аксай-3", "almaty-aujezovskij-mkr-aksay-3"],
  ["аксай 3", "almaty-aujezovskij-mkr-aksay-3"],
  ["аксай-3", "almaty-aujezovskij-mkr-aksay-3"],
  ["мкр аксай 4", "almaty-aujezovskij-mkr-aksay-4"],
  ["мкр аксай-4", "almaty-aujezovskij-mkr-aksay-4"],
  ["аксай 4", "almaty-aujezovskij-mkr-aksay-4"],
  ["аксай-4", "almaty-aujezovskij-mkr-aksay-4"],
  ["мкр аксай 5", "almaty-aujezovskij-mkr-aksay-5"],
  ["мкр аксай-5", "almaty-aujezovskij-mkr-aksay-5"],
  ["аксай 5", "almaty-aujezovskij-mkr-aksay-5"],
  ["аксай-5", "almaty-aujezovskij-mkr-aksay-5"],
  ["алматы", "almaty"],
  ["астана", "astana"],
  ["астане", "astana"],
  ["астану", "astana"],
  ["астаны", "astana"],
  ["нур султан", "astana"],
  ["нурсултан", "astana"],
  ["шымкент", "shymkent"],
  ["шымкенте", "shymkent"],
  ["актау", "aktau"],
  ["актобе", "aktobe"],
  ["атырау", "atyrau"],
  ["караганда", "karaganda"],
  ["караганде", "karaganda"],
  ["костанай", "kostanaj"],
  ["костанае", "kostanaj"],
  ["кокшетау", "kokshetau"],
  ["конаев", "konaev"],
  ["каскелен", "kaskelen"],
  ["кызылорда", "kyzylorda"],
  ["кызылорде", "kyzylorda"],
  ["павлодар", "pavlodar"],
  ["павлодаре", "pavlodar"],
  ["петропавловск", "petropavlovsk"],
  ["петропавловске", "petropavlovsk"],
  ["семей", "semej"],
  ["семее", "semej"],
  ["уральск", "uralsk"],
  ["уральске", "uralsk"],
  ["усть каменогорск", "ust-kamenogorsk"],
  ["усть-каменогорск", "ust-kamenogorsk"],
  ["усть каменогорске", "ust-kamenogorsk"],
  ["усть-каменогорске", "ust-kamenogorsk"],
  ["тараз", "taraz"],
  ["таразе", "taraz"],
  ["туркестан", "turkestan"],
  ["туркестане", "turkestan"],
  ["талдыкорган", "taldykorgan"],
  ["талдыкоргане", "taldykorgan"],
  ["талгар", "almatinskaya-oblast/talgar"],
  ["талгаре", "almatinskaya-oblast/talgar"],
  ["темиртау", "temirtau"],
  ["экибастуз", "ekibastuz"],
  ["рудный", "rudnyj"],
  ["жезказган", "zhezkazgan"],
  ["байконур", "bajkonur"],
  ["аксай", "aksaj"],
  ["бесагаш", "besagash-dzerzhinskoe"],
  ["бесагаш дзержинское", "besagash-dzerzhinskoe"],
  ["алматинская область", "almatinskaya-oblast"],
  ["алматинской области", "almatinskaya-oblast"],
  ["область алматы", "almatinskaya-oblast"],
  ["актюбинская область", "aktjubinskaja-oblast"],
  ["актюбинской области", "aktjubinskaja-oblast"],
  ["атырауская область", "atyrauskaja-oblast"],
  ["атырауской области", "atyrauskaja-oblast"],
  ["карагандинская область", "karagandinskaja-oblast"],
  ["карагандинской области", "karagandinskaja-oblast"],
  ["костанайская область", "kostanajskaja-oblast"],
  ["костанайской области", "kostanajskaja-oblast"],
  ["кызылординская область", "kyzylordinskaja-oblast"],
  ["кызылординской области", "kyzylordinskaja-oblast"],
  ["мангистауская область", "mangistauskaja-oblast"],
  ["мангистауской области", "mangistauskaja-oblast"],
  ["павлодарская область", "pavlodarskaja-oblast"],
  ["павлодарской области", "pavlodarskaja-oblast"],
  ["северо казахстанская область", "severo-kazahstanskaja-oblast"],
  ["северо-казахстанская область", "severo-kazahstanskaja-oblast"],
  ["восточно казахстанская область", "vostochno-kazahstanskaja-oblast"],
  ["восточно-казахстанская область", "vostochno-kazahstanskaja-oblast"],
  ["западно казахстанская область", "zapadno-kazahstanskaja-oblast"],
  ["западно-казахстанская область", "zapadno-kazahstanskaja-oblast"],
  ["жамбылская область", "zhambylskaja-oblast"],
  ["жамбылской области", "zhambylskaja-oblast"],
  ["область абай", "abay-oblast"],
  ["абайская область", "abay-oblast"],
  ["жетысуская область", "jetisyskaya-oblast"],
  ["область жетысу", "jetisyskaya-oblast"],
  ["улытауская область", "ulitayskay-oblast"],
  ["область улытау", "ulitayskay-oblast"],
];

export const EXTRA_GEO_NODES = [
  {
    name: "Алатауский р-н",
    slug: "almaty-alatauskij",
    type: "district",
    url_path: "almaty-alatauskij",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "Алмалинский р-н",
    slug: "almaty-almalinskij",
    type: "district",
    url_path: "almaty-almalinskij",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "Ауэзовский р-н",
    slug: "almaty-aujezovskij",
    type: "district",
    url_path: "almaty-aujezovskij",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "Бостандыкский р-н",
    slug: "almaty-bostandykskij",
    type: "district",
    url_path: "almaty-bostandykskij",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "Жетысуский р-н",
    slug: "almaty-zhetysuskij",
    type: "district",
    url_path: "almaty-zhetysuskij",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "Медеуский р-н",
    slug: "almaty-medeuskij",
    type: "district",
    url_path: "almaty-medeuskij",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "Наурызбайский р-н",
    slug: "almaty-nauryzbajskiy",
    type: "district",
    url_path: "almaty-nauryzbajskiy",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "Турксибский р-н",
    slug: "almaty-turksibskij",
    type: "district",
    url_path: "almaty-turksibskij",
    parent_url_path: "almaty",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "мкр Аксай-1",
    slug: "almaty-aujezovskij-mkr-aksay-1",
    type: "microdistrict",
    url_path: "almaty-aujezovskij-mkr-aksay-1",
    parent_url_path: "almaty-aujezovskij",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "мкр Аксай-2",
    slug: "almaty-aujezovskij-mkr-aksay-2",
    type: "microdistrict",
    url_path: "almaty-aujezovskij-mkr-aksay-2",
    parent_url_path: "almaty-aujezovskij",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "мкр Аксай-3",
    slug: "almaty-aujezovskij-mkr-aksay-3",
    type: "microdistrict",
    url_path: "almaty-aujezovskij-mkr-aksay-3",
    parent_url_path: "almaty-aujezovskij",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "мкр Аксай-4",
    slug: "almaty-aujezovskij-mkr-aksay-4",
    type: "microdistrict",
    url_path: "almaty-aujezovskij-mkr-aksay-4",
    parent_url_path: "almaty-aujezovskij",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
  {
    name: "мкр Аксай-5",
    slug: "almaty-aujezovskij-mkr-aksay-5",
    type: "microdistrict",
    url_path: "almaty-aujezovskij-mkr-aksay-5",
    parent_url_path: "almaty-aujezovskij",
    verified: true,
    in_sitemap: false,
    name_source: "krisha-public-filter",
  },
];

export const CATEGORY_ALIASES: Array<
  [
    alias: string,
    slug:
      | "prodazha/kvartiry"
      | "prodazha/uchastkov"
      | "prodazha/doma-dachi"
      | "prodazha/kommercheskaya-nedvizhimost",
  ]
> = [
  ["двушка", "prodazha/kvartiry"],
  ["двухкомнатная", "prodazha/kvartiry"],
  ["двухкомнатную", "prodazha/kvartiry"],
  ["однушка", "prodazha/kvartiry"],
  ["однокомнатная", "prodazha/kvartiry"],
  ["трёшка", "prodazha/kvartiry"],
  ["трешка", "prodazha/kvartiry"],
  ["трехкомнатная", "prodazha/kvartiry"],
  ["трёхкомнатная", "prodazha/kvartiry"],
  ["квартира", "prodazha/kvartiry"],
  ["квартиры", "prodazha/kvartiry"],
  ["квартиру", "prodazha/kvartiry"],
  ["апартаменты", "prodazha/kvartiry"],
  ["дом", "prodazha/doma-dachi"],
  ["дома", "prodazha/doma-dachi"],
  ["дача", "prodazha/doma-dachi"],
  ["дачи", "prodazha/doma-dachi"],
  ["участок", "prodazha/uchastkov"],
  ["участки", "prodazha/uchastkov"],
  ["земельный участок", "prodazha/uchastkov"],
  ["земельные участки", "prodazha/uchastkov"],
  ["земля", "prodazha/uchastkov"],
  ["коммерция", "prodazha/kommercheskaya-nedvizhimost"],
  ["коммерческая недвижимость", "prodazha/kommercheskaya-nedvizhimost"],
  ["офис", "prodazha/kommercheskaya-nedvizhimost"],
  ["магазин", "prodazha/kommercheskaya-nedvizhimost"],
];
